FROM ubi8/ubi:8.3

MAINTAINER  train_ed  <train_ed@gmail.com>

ARG         NEXUS_VERSION=2.14.3-02

ENV         NEXUS_HOME=/opt/nexus

RUN         yum install -y java-1.8.0-openjdk-devel && \
            yum clean all

RUN         useradd -u 1001 -g 10001 nexus 

RUN         chmod 775 ${NEXUS_HOME}/ 

ADD         nexus-2.14.3-02-bundle.tar.gz ${NEXUS_HOME}/
ADD         ./nexus-start.sh   ${NEXUS_HOME}/

RUN         ln -s ${NEXUS_HOME}/nexus-${NEXUS_VERSION} ${NEXUS_HOME}/nexus2 && \
            chmod -R nexus:nexus ${NEXUS_HOME}

USER        nexus
WORKDIR     /opt/nexus/

VOLUME      /opt/nexus/sonatype-work
